// Code generated by go-swagger; DO NOT EDIT.


// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0


package daemon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  "context"
  "fmt"
  "net/http"
  "time"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  cr "github.com/go-openapi/runtime/client"
  "github.com/go-openapi/strfmt"
  "github.com/go-openapi/swag"
  "github.com/go-openapi/validate"

  	"github.com/cilium/cilium/api/v1/client/bgp"
	"github.com/cilium/cilium/api/v1/client/daemon"
	"github.com/cilium/cilium/api/v1/client/endpoint"
	"github.com/cilium/cilium/api/v1/client/ipam"
	"github.com/cilium/cilium/api/v1/client/policy"
	"github.com/cilium/cilium/api/v1/client/prefilter"
	"github.com/cilium/cilium/api/v1/client/recorder"
	"github.com/cilium/cilium/api/v1/client/service"
	"github.com/cilium/cilium/api/v1/models"
  
)

// NewGetCgroupDumpMetadataParams creates a new GetCgroupDumpMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCgroupDumpMetadataParams() *GetCgroupDumpMetadataParams {
  return &GetCgroupDumpMetadataParams{
    timeout: cr.DefaultTimeout,
  }
}

// NewGetCgroupDumpMetadataParamsWithTimeout creates a new GetCgroupDumpMetadataParams object
// with the ability to set a timeout on a request.
func NewGetCgroupDumpMetadataParamsWithTimeout(timeout time.Duration) *GetCgroupDumpMetadataParams {
  return &GetCgroupDumpMetadataParams{
    timeout: timeout,
  }
}

// NewGetCgroupDumpMetadataParamsWithContext creates a new GetCgroupDumpMetadataParams object
// with the ability to set a context for a request.
func NewGetCgroupDumpMetadataParamsWithContext(ctx context.Context) *GetCgroupDumpMetadataParams {
  return &GetCgroupDumpMetadataParams{
    Context: ctx,
  }
}

// NewGetCgroupDumpMetadataParamsWithHTTPClient creates a new GetCgroupDumpMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCgroupDumpMetadataParamsWithHTTPClient(client *http.Client) *GetCgroupDumpMetadataParams {
  return &GetCgroupDumpMetadataParams{
    HTTPClient: client,
  }
}

/* GetCgroupDumpMetadataParams contains all the parameters to send to the API endpoint
   for the get cgroup dump metadata operation.

   Typically these are written to a http.Request.
*/
type GetCgroupDumpMetadataParams struct {

  timeout time.Duration
  Context context.Context
  HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cgroup dump metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCgroupDumpMetadataParams) WithDefaults() *GetCgroupDumpMetadataParams {
    o.SetDefaults()
    return o
}

// SetDefaults hydrates default values in the get cgroup dump metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCgroupDumpMetadataParams) SetDefaults() {
  // no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) WithTimeout(timeout time.Duration) *GetCgroupDumpMetadataParams {
  o.SetTimeout(timeout)
  return o
}

// SetTimeout adds the timeout to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) SetTimeout(timeout time.Duration) {
  o.timeout = timeout
}

// WithContext adds the context to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) WithContext(ctx context.Context) *GetCgroupDumpMetadataParams {
  o.SetContext(ctx)
  return o
}

// SetContext adds the context to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) SetContext(ctx context.Context) {
  o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) WithHTTPClient(client *http.Client) *GetCgroupDumpMetadataParams {
  o.SetHTTPClient(client)
  return o
}

// SetHTTPClient adds the HTTPClient to the get cgroup dump metadata params
func (o *GetCgroupDumpMetadataParams) SetHTTPClient(client *http.Client) {
  o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCgroupDumpMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

  if err := r.SetTimeout(o.timeout); err != nil {
    return err
  }
  var res []error

  if len(res) > 0 {
    return errors.CompositeValidationError(res...)
  }
  return nil
}
