// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  "github.com/go-openapi/strfmt"
  	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AllocationMap Map of allocated IPs
// 
//
// swagger:model AllocationMap
    type AllocationMap map[string]string
  
// Validate validates this allocation map
func (m AllocationMap) Validate(formats strfmt.Registry) error {
  return nil
}
// ContextValidate validates this allocation map based on context it is used 
func (m AllocationMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
  return nil
}



