// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
  "github.com/go-openapi/strfmt"
  	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigurationMap Map of configuration key/value pairs.
// 
//
// swagger:model ConfigurationMap
    type ConfigurationMap map[string]string
  
// Validate validates this configuration map
func (m ConfigurationMap) Validate(formats strfmt.Registry) error {
  return nil
}
// ContextValidate validates this configuration map based on context it is used 
func (m ConfigurationMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
  return nil
}



