


// Code generated by go-swagger; DO NOT EDIT.


// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0


package recorder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command


import (
  "fmt"
  "net/http"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/runtime/security"
  "github.com/go-openapi/swag"
  "github.com/go-openapi/validate"
  "github.com/go-openapi/runtime/middleware"

  	"github.com/cilium/cilium/api/v1/models"
	"github.com/cilium/cilium/api/v1/server/restapi/bgp"
	"github.com/cilium/cilium/api/v1/server/restapi/daemon"
	"github.com/cilium/cilium/api/v1/server/restapi/endpoint"
	"github.com/cilium/cilium/api/v1/server/restapi/ipam"
	"github.com/cilium/cilium/api/v1/server/restapi/policy"
	"github.com/cilium/cilium/api/v1/server/restapi/prefilter"
	"github.com/cilium/cilium/api/v1/server/restapi/recorder"
	"github.com/cilium/cilium/api/v1/server/restapi/service"
  	"github.com/cilium/cilium/api/v1/server/restapi"
)



// GetRecorderOKCode is the HTTP code returned for type GetRecorderOK
const GetRecorderOKCode int = 200

/*GetRecorderOK Success

swagger:response getRecorderOK
*/
type GetRecorderOK struct {
  
  
  /*
  In: Body
  */
  Payload []*models.Recorder `json:"body,omitempty"`
  
}

// NewGetRecorderOK creates GetRecorderOK with default headers values
func NewGetRecorderOK() *GetRecorderOK { 

  return &GetRecorderOK{
    
    }
}


// WithPayload adds the payload to the get recorder o k response
func (o *GetRecorderOK) WithPayload(payload []*models.Recorder) *GetRecorderOK {
  o.Payload = payload
  return o
}

// SetPayload sets the payload to the get recorder o k response
func (o *GetRecorderOK) SetPayload(payload []*models.Recorder) {
  o.Payload = payload
}


// WriteResponse to the client
func (o *GetRecorderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
  
  
  rw.WriteHeader(200)
    payload := o.Payload
    if payload == nil {
      // return empty array
      payload =make([]*models.Recorder, 0, 50)
    }
    
    if err := producer.Produce(rw, payload); err != nil {
      panic(err) // let the recovery middleware deal with this
    }
}







