name: Approve PR

on:
  pull_request:
    types:
    - review_requested

jobs:
  approve:
    environment: auto-approve

    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: |
        echo ${{ github.event.pull_request.user.login }}
        echo ${{ github.triggering_actor }}
        echo ${{ github.event.requested_reviewer.login }}

    - name: Approve PR
      # Approve the PR if all of the following conditions are true:
      # - the PR review was requested by renovate bot and
      # - the PR was also created by renovate bot
      # - the requested reviewer was the trusted 'ciliumbot'
      if: ${{
           github.event.pull_request.user.login == 'private-renovate-2[bot]' &&
           github.triggering_actor == 'private-renovate-2[bot]' &&
           github.event.requested_reviewer.login == 'aanm'
          }}
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo $PERSONAL_ACCESS_TOKEN | gh auth login --with-token
        gh -R ${GITHUB_REPOSITORY} pr review ${PULL_REQUEST_NUMBER} --approve
